### PR TITLE
Instruments support

### PR DESCRIPTION
**Pull request by MyBlackMIDIScore**
For any questions/clarifications, please ask here because I can't use Discord at the moment.

The only thing I am currently not very sure about is the search by bank and preset on soundfont/mod.rs line 583. I don't know how much of a performance impact this will have, but I could change it to be like the spawner params (128*128 vector of Option\<Instrument\> or something like that).

Also with this we should be good to start SF2 support :)

This is part of a GM MIDI rendered with XSynth (AIG + Arachno): [rach2-arachno-xsynth.zip](https://github.com/arduano/xsynth/files/12649371/rach2-arachno-xsynth.zip)

Here's also a build of Forte with instruments support so you can test it out if you wish (code is in the `instruments` branch): [forte.zip](https://github.com/arduano/xsynth/files/12649427/forte.zip)

### CODE REVIEW

**Comment by arduano** [comment]
Looks pretty good, well written, my only question is, does drums_only get set anywhere other than having the option in individual channels? Like can xsynth realtime make use of it? I don't think I noticed a place where that happens.

Other than that, good idea on just re-building the matrix each time a program is changed, main reason I didn't do this was because I thought adding an extra dimension to the matrix would eat up a lot of ram, but I guess changing programs is so infrequent that just rebuilding the matrix is ok.

I guess another concern is memory usage, with all programs in the soundfont being loaded in memory for each key (even if the key's audio isn't actually part of the soundfont, we interpolate and store it anyway, at a fairly high sample rate).

But otherwise looks goodl.

**Comment by MyBlackMIDIScore** [comment]
> Looks pretty good, well written, my only question is, does drums_only get set anywhere other than having the option in individual channels? Like can xsynth realtime make use of it? I don't think I noticed a place where that happens.
Oh yeah I forgot about those, I just pushed another commit that implements those changes on the other modules as well.

> Other than that, good idea on just re-building the matrix each time a program is changed, main reason I didn't do this was because I thought adding an extra dimension to the matrix would eat up a lot of ram, but I guess changing programs is so infrequent that just rebuilding the matrix is ok.
Yeah it's pretty infrequent but I am still a bit worried about the performance of it, since on every program change the `.find` function from `get_attack_voice_spawners_at` is called 128^2 times and it must be pretty slow. What do you think about storing programs like the voice spawners (in a 128^2 vector of options) like I mentioned before? Idk if this will help

> I guess another concern is memory usage, with all programs in the soundfont being loaded in memory for each key (even if the key's audio isn't actually part of the soundfont, we interpolate and store it anyway, at a fairly high sample rate).
Isn't everything in the soundfont stored in an Arc anyway? I mean I don't know exactly how it works, but I feel like it won't make a difference at all.

**Comment by arduano** [comment]
> What do you think about storing programs like the voice spawners (in a 128^2 vector of options) like I mentioned before
It actually uses a surprising amount of memory still, I think it's better to keep your current approach

> Isn't everything in the soundfont stored in an Arc anyway
Well yes, but it still stores each key's sample at a high sample rate as stereo float32s, it's the reason xsynth already uses so much ram, and it will be multiplied by each program that the soundfont has.

**Comment by MyBlackMIDIScore** [comment]
> It actually uses a surprising amount of memory still, I think it's better to keep your current approach

Alright then we can keep this unless we find some better way in the future

> Well yes, but it still stores each key's sample at a high sample rate as stereo float32s, it's the reason xsynth already uses so much ram, and it will be multiplied by each program that the soundfont has.

Yeah that's true, but also kind of unavoidable. It's just like loading multiple SFZs in the list and keeping them all in memory. All synths load all the programs in RAM.
The only thing I can think we can do to kind of improve this is by making some kind of generic sample type that can hold i16, i32 or f32 as samples depending on the soundfont's original format. This way soundfonts with i16 sample type will not need to be converted to f32 and will use much less RAM. There is something similar in the `fundsp` library IIRC. That would be for another PR though.

**Comment by arduano** [comment]
Yeah for the memory part, I don't know any efficient way of approaching this other than lazy loading the soundfonts, or interpolating properly for each voice rather than pre-interpolating beforehand, so not sure.

We can probably merge as-is, though you should check the memory usage just in case.

**Comment by MyBlackMIDIScore** [comment]
> interpolating properly for each voice rather than pre-interpolating beforehand

Would this make a difference? I mean, aren't the samples re-sampled according to the output's sample rate anyway?
I'm saying this because in most cases it's 48k or 44.1k which would usually be the same as the original sample.

> check the memory usage

I did some memory tests with bytehound and the usage and allocations are the same as before when loading one or multiple soundfonts.

### master:
memory-master

### instruments:
memory-instruments

I am not sure what else to check about memory usage.

**Comment by arduano** [comment]
> Would this make a difference? 
Yes, it would make a hissing sound. Kinda like we already have in some cases with pitch bends, but it would happen much much more often.

> in most cases it's 48k or 44.1k which would usually be the same as the original sample
I believe we re-sample everything to like 192k or something high like that, so that pitch bends don't create as much hissing.

The memory usage feels a bit weird, but I guess that could be explained by the master branch still loading all instruments, but just choosing the piano always.

**Review by arduano — APPROVED** [review]

**Review by Kaydax — APPROVED** [review]

**Comment by MyBlackMIDIScore** [comment]
I just took a quick look at the code and when loading the samples they are resampled to the output's sample rate (from stream_params) so the only thing increasing the memory usage is using f32 for the samples (instead of i16 or i24 which is usually the sample's original). 

But yeah anyway this can be for another PR (with a generic sample type or sth), so I'll merge this for now.

**Pull request merged**
